service: bincollection

provider:
  name: aws
  runtime: python2.7
  stage: prod
  region: eu-west-1
  events: alexaSkill
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource:
         Fn::Join:
           - ""
           - - arn:aws:dynamodb:${self:provider.region}:*:table/
             - Ref: usersTable

functions:
  skill:
    handler: handler.lambda_handler
    events:
      - alexaSkill

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BinCollectionUsers
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
